### PR TITLE
Added ppc64le build for cuda 11.6

### PR DESCRIPTION
**Pull request by alhad-deshpande**
1. Added recipe for ppc64le with cuda 11.6 in conda_build_config.yaml file.
2. Ran conda smithy rerender to generate .ci_support/linux_ppc64le_cuda_compiler_version11.6.yaml file and to add enty in .azure-pipelines/azure-pipelines-linux.yml.
3. The build number has not been bumped up.

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by alhad-deshpande** [comment]
@leofang 
Can you please review/approve the PR?

**Review by kkraus14 — APPROVED** [review]

**Comment by kkraus14** [comment]
@alhad-deshpande I believe the build number in the recipe needs to be bumped and then this should be good to go

**Comment by alhad-deshpande** [comment]
> @alhad-deshpande I believe the build number in the recipe needs to be bumped and then this should be good to go

@kkraus14 
The build number in meta.yaml is 0, so did not changed that.

**Comment by kkraus14** [comment]
> > @alhad-deshpande I believe the build number in the recipe needs to be bumped and then this should be good to go
> 
> @kkraus14 The build number in meta.yaml is 0, so did not changed that.

Even though you're just adding the ppc64le CUDA 11.6 build, it will produce new builds of the other versions as well so we need to bump the build number to avoid clobbering those builds.

**Comment by jakirkham** [comment]
That's right. Please try the existing packages out and let us know how that goes 🙂

**Comment by alhad-deshpande** [comment]
@leofang @kkraus14 @jakirkham 
Below are the reasons to build on 11.6
1. I want to build CUDF 21.12.00 as well. The CUDF documentation says that it requires CUDA 11.5+ (https://github.com/rapidsai/cudf/blob/v21.12.00/CONTRIBUTING.md#setting-up-your-build-environment). When I tried building CUDF 21.12.00 with CUDA 11.2 I got some reference not found issues. Hence thought that it would be better if entire chain RMM->CUDF->NVTabuar is built with CUDA 11.6.
2. I am creating conda env with CUDA 11.6 by using below command.
    conda create -y -n nvtabular_dev_11.6 -c conda-forge cudatoolkit=11.6
    After activating above env when tried installing existing RMM package with below command.
    conda install -c conda-forge librmm=21.12.00

    Got below error:
    UnsatisfiableError: The following specifications were found to be incompatible with a past
explicit spec that is not an explicit spec in this operation (cudatoolkit):

  - librmm=21.12.00 -> cudatoolkit[version='10.2|10.2.*']

Please let me know your views.

**Comment by alhad-deshpande** [comment]
@leofang @kkraus14 @jakirkham
Bumped up the build version to 1 in meta.yaml.

**Comment by leofang** [comment]
Hi @alhad-deshpande thanks for checking. I see the problem. The ppc64le + CUDA 11.x support was only built for the latest version (22.02); for 21.12 we only had ppc64le + CUDA 10.2, hence the solver error. Does the latest version work for you, or you'd really prefer 21.12?

**Comment by alhad-deshpande** [comment]
> 

@leofang 
Yes, 21.12.00 is preferred as latest one some more dependencies. I have built the RMM 21.12.00 and CUDF 21.12.00 on POWER locally and that is working for now. Just wanted these available on conda.

**Comment by leofang** [comment]
Understood. Given that it's my oversight (I should have done the PR in two steps, one for ppc64le support and then another for updating to 22.02) and that only maintainers can create additional branches on a feedstock, I am sending a PR to rebuild 21.12 (#20).

**Comment by leofang** [comment]
@alhad-deshpande could you retry `conda install -c conda-forge librmm=21.12.00 cudatoolkit=11.6` please?

**Comment by alhad-deshpande** [comment]
> @alhad-deshpande could you retry `conda install -c conda-forge librmm=21.12.00 cudatoolkit=11.6` please?

This works on ppc64le. Thanks for generating new PR. Also this only installs librmm, can we also add rmm python package something lilke below.
conda install -c conda-forge rmm=21.12.00 (which inherently will install librmm as well)

Can you please help me with the process?

**Comment by leofang** [comment]
Thanks, @alhad-deshpande, let me close this PR since it's no longer needed.

I think it is fine to either make this feedstock generate [multiple outputs](https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#outputs-section), or create a new, dedicated feedstock [via staged-recipes](https://conda-forge.org/docs/maintainer/adding_pkgs.html#contributing-packages). 

You can also upload the locally built package to your own Anaconda channel instead of using conda-forge's infrastructure, as suggested elsewhere, but generally I'd encourage contributions to the community 🙂

I think the name `rmm` would indeed fit the naming convention adopted by the RAPIDS folks.

**Comment by alhad-deshpande** [comment]
> 

Thanks @leofang for your help.

**Pull request closed without merging**
