### PR TITLE
Migration to spdlog 1.9

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
Currently there is a migration running to spdlog=1.9 (see https://conda-forge.org/status/#spdlog190). This feedstock could not be migrated by the bot as the spdlog version was pinned in the `meta.yaml`. This PR gets rid of this pinning and rerenders to that spdlog 1.9 is pulled in.

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
This is ready for review. Thanks @conda-forge/librmm

**Review by kkraus14 — APPROVED** [review]

**Comment by kkraus14** [comment]
Thanks @Tobias-Fischer!

**Pull request merged**
