### PR TITLE
Update to 23.08

### PR DESCRIPTION
**Pull request by kkraus14**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Closes https://github.com/conda-forge/librmm-feedstock/pull/57

### CODE REVIEW

**Comment by kkraus14** [comment]
@conda-forge-admin, please rerender

**Review by jakirkham — APPROVED** [review]

**Comment by jakirkham** [comment]
Dropped automerge while we figure out what order we want to merge these in

xref: https://github.com/conda-forge/librmm-feedstock/pull/51#issuecomment-1699730784

**Comment by kkraus14** [comment]
Rebased after the CUDA 11.8 / 12 migrators were added, so this should be good to go now, will tackle #48 after this lands

**Review by jakirkham — APPROVED** [review]

**Comment by kkraus14** [comment]
CI job is stuck so just going to merge #57 since it's equivalent anyway.

**Pull request closed without merging**
