### PR TITLE
Use relative path for `CMAKE_INSTALL_LIBDIR`

### PR DESCRIPTION
**Pull request by robertmaynard**
The `CMAKE_INSTALL_LIBDIR` needs to be relative for the CCCL-config.cmake packaged with librmm to work properly.

This is exactly what the upstream rapidsai version of librmm does ( https://github.com/rapidsai/rmm/blob/branch-24.04/conda/recipes/librmm/build.sh#L3 )

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)

### CODE REVIEW

**Review by kkraus14 — APPROVED** [review]

**Comment by kkraus14** [comment]
> The CMAKE_INSTALL_LIBDIR needs to be relative for the CCCL-config.cmake packaged with librmm to work properly

We can make the change here, but this seems like a bug in the `CCCL-config.cmake`? Can this be fixed upstream as well?

**Comment by robertmaynard** [comment]
> > The CMAKE_INSTALL_LIBDIR needs to be relative for the CCCL-config.cmake packaged with librmm to work properly
> 
> We can make the change here, but this seems like a bug in the `CCCL-config.cmake`? Can this be fixed upstream as well?

Absolute values for `CMAKE_INSTALL_LIBDIR` aren't truly fully supported by cmake, since the `cmake --install <dir> --prefix` command will cause a `CMAKE_INSTALL_PREFIX` to change, but not recompute things like `CMAKE_INSTALL_LIBDIR`.

This will cause any generated `<project>-targets.cmake` to be fundamentally broken as they will reference the `CMAKE_INSTALL_PREFIX` that was computed at configure time, and not the one at install time via the `--prefix` command.

While `CCCL` can be updated to better support absolute `CMAKE_INSTALL_LIBDIR` values, no promise can be made about correct/valid installations due to fundamental issue around using absolute values.

**Review by jakirkham — APPROVED** [review]

**Comment by jakirkham** [comment]
As to `CCCL-config.cmake`, would it make sense to file an issue on RMM (or maybe also CCCL)?

**Comment by robertmaynard** [comment]
> As to `CCCL-config.cmake`, would it make sense to file an issue on RMM (or maybe also CCCL)?
CCCL issue has been opened:
https://github.com/NVIDIA/cccl/issues/1390

**Review by kkraus14 — APPROVED** [review]

**Comment by jakirkham** [comment]
Thanks Robert and Keith! 🙏

**Pull request merged**
